CREATE TABLE `brand_style_profiles` (
	`id` text PRIMARY KEY NOT NULL,
	`user_id` text NOT NULL,
	`name` text NOT NULL,
	`description` text,
	`primary_colors` text NOT NULL,
	`secondary_colors` text,
	`color_mood` text,
	`typography_style` text,
	`headline_weight` text,
	`imagery_approach` text NOT NULL,
	`artistic_references` text,
	`lighting_preference` text,
	`composition_style` text,
	`mood_descriptors` text,
	`texture_preference` text,
	`aspect_ratio_preference` text,
	`depth_of_field` text,
	`style_prefix` text,
	`style_suffix` text,
	`negative_concepts` text,
	`reference_image_urls` text,
	`is_active` integer DEFAULT false,
	`created_at` integer,
	`updated_at` integer
);
