import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | LinWheel",
  description: "Terms of Service for LinWheel",
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950 py-16 px-6">
      <div className="max-w-3xl mx-auto">
        <h1 className="text-3xl font-bold text-zinc-900 dark:text-zinc-100 mb-8">
          Terms of Service
        </h1>

        <div className="prose prose-zinc dark:prose-invert max-w-none space-y-6">
          <p className="text-zinc-600 dark:text-zinc-400">
            Last updated: {new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}
          </p>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-100 mt-8 mb-4">
              1. Acceptance of Terms
            </h2>
            <p className="text-zinc-600 dark:text-zinc-400">
              By using LinWheel, you agree to these Terms of Service. If you do not agree,
              please do not use the service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-100 mt-8 mb-4">
              2. Description of Service
            </h2>
            <p className="text-zinc-600 dark:text-zinc-400">
              LinWheel is a content generation tool that helps you create LinkedIn posts,
              articles, and carousel images using AI. You can optionally connect your LinkedIn
              account to publish content directly.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-100 mt-8 mb-4">
              3. User Responsibilities
            </h2>
            <p className="text-zinc-600 dark:text-zinc-400">
              You are responsible for:
            </p>
            <ul className="list-disc pl-6 text-zinc-600 dark:text-zinc-400 space-y-2 mt-2">
              <li>Reviewing and editing AI-generated content before publishing</li>
              <li>Ensuring your content complies with LinkedIn&apos;s terms of service</li>
              <li>Maintaining the security of your account credentials</li>
              <li>Any content you publish to LinkedIn using our service</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-100 mt-8 mb-4">
              4. AI-Generated Content
            </h2>
            <p className="text-zinc-600 dark:text-zinc-400">
              Content generated by LinWheel is created using AI models. While we strive for
              quality, you should review all content before publishing. You retain ownership
              of the content you create and publish.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-100 mt-8 mb-4">
              5. Limitation of Liability
            </h2>
            <p className="text-zinc-600 dark:text-zinc-400">
              LinWheel is provided &quot;as is&quot; without warranties. We are not liable for any
              damages arising from your use of the service or content published through it.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-100 mt-8 mb-4">
              6. Changes to Terms
            </h2>
            <p className="text-zinc-600 dark:text-zinc-400">
              We may update these terms at any time. Continued use of the service after
              changes constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold text-zinc-900 dark:text-zinc-100 mt-8 mb-4">
              7. Contact
            </h2>
            <p className="text-zinc-600 dark:text-zinc-400">
              For questions about these terms, contact us at support@linwheel.com
            </p>
          </section>
        </div>

        <div className="mt-12 pt-8 border-t border-zinc-200 dark:border-zinc-800">
          <a
            href="/"
            className="text-blue-600 dark:text-blue-400 hover:underline"
          >
            &larr; Back to LinWheel
          </a>
        </div>
      </div>
    </div>
  );
}
